title: anchorcell
description: "cloud rap electropop things"
url: "https://anchorcell.net"
baseurl: ""
permalink: pretty
markdown: kramdown

plugins:
  - jekyll-paginate


paginate: 10
paginate_path: "/news/page:num/"
